# Generated by Django 5.2.5 on 2025-08-14 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programas.programa', verbose_name='Programa de Formación'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
