# Generated by Django 5.2.4 on 2025-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('documento_identidad', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono_principal', models.CharField(max_length=15, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Secundario')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('nivel_educativo', models.CharField(choices=[('LICENCIADO', 'Licenciado'), ('INGENIERO', 'Ingeniero'), ('MAGISTER', 'Magíster'), ('DOCTOR', 'Doctor')], help_text='Ej: Licenciado, Ingeniero, Magíster, Doctor', max_length=100, verbose_name='Nivel Educativo')),
                ('titulo_profesional', models.CharField(max_length=150, verbose_name='Título Profesional')),
                ('universidad', models.CharField(max_length=100, verbose_name='Universidad/Institución')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Área de Especialidad')),
                ('experiencia_anos', models.PositiveIntegerField(verbose_name='Años de Experiencia')),
                ('modalidad_trabajo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta')], default='PRESENCIAL', max_length=10, verbose_name='Modalidad de Trabajo')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'En Vacaciones'), ('LICENCIA', 'En Licencia')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('codigo_instructor', models.CharField(max_length=20, unique=True, verbose_name='Código de Instructor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
